### ISSUE TITLE
WP desaturates images upon upload

### ISSUE THREAD

**Issue by tgilliss** [a8cteam51/onbeing#103]
Several web producers noticed that WordPress is slightly desaturating the red tones in the images we upload and thus rendering rich photographs rather dull. Is there a setting or a WP plugin or some other suggestion you might have that would streamline this process without degrading the image?

Right now we have to go through a convoluted process with Photoshop each time and take a lot of additional steps. Any advice or fix is appreciated!

**Comment by ChrisHardie** [comment]
@tgilliss Do you have an example you can share, in the form of the source image file available before uploading to WordPress and the URL of the desaturated result? It would also be useful to know the exact steps you're taking to upload the image so we can try to reproduce this and then look at possible solutions. Thanks!

**Comment by tgilliss** [comment]
Hey there.

The process is just uploading a featured image — no matter if it's through
the media assets manager directly or via the featured image episode
uploader within an episode.

Attached is the original source image from Getty Images. When you upload it
to the system, it strips out the color profile and makes it look flat and
bland. Desaturates it a bit. Try this first, then...

Here's an image that's been put through a Photoshop process by one of our
producers. Upon upload, the color profile is preserved: https://i2.wp.com/
onbeing.org/wp-content/uploads/2017/08/2017-Mary-Catherine-Bateson-lead-
nocolormanage.jpg?fit=1200%2C841&ssl=1

Is there a way for WordPress to handle this?

Thank you.
T

...................
*Trent Gilliss*
Editor-in-Chief / Publisher / Cofounder
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by michiecat** [comment]
Hi @tgilliss! Would you be able to email the image attachment to concierge@wordpress.com? Unfortunately, attachments don't come through here on Github. Alternatively you could upload the image directly to the Github issue by dragging and dropping it into the comment box. 

That said, I did some research, and this is a known issue with WordPress. WordPress creates several different image sizes when you upload them into the media library, and these are essentially new images, all using the RGB colorspace. Images that have not been converted to this colorspace before uploading can lose saturation due to this colorspace supporting fewer colors. 

To prevent saturation loss, you can try saving them sRGB color space in Photoshop or which ever image editor you use, prior to uploading. This article outlines the steps to do so a bit more: http://enviragallery.com/how-to-fix-the-image-desaturation-issue-in-wordpress/

Let us know if these methods don't work.

**Comment by michiecat** [comment]
@tgilliss checking in with you on this. Did you get a chance to try some of these recommendations out?

**Comment by tgilliss** [comment]
Hi Michelle. Yes, we currently use these processes and were hoping for a
more expedient solution. Regardless, we'll continue to upload in this way
and try to figure out how we can standardize this process for all our
producers.

...................
*Trent Gilliss*
Editor-in-Chief / Publisher / Cofounder
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Mon, Aug 28, 2017 at 4:52 PM, Michelle Langston <notifications@github.com

**Comment by michiecat** [comment]
Yes, I understand that it's not the most ideal solution, but it's the best one that I've been able to find so far. It's a known issue with WordPress. I am hesitant to recommend plugins because they aren't as sustainable as handling the image pre-processing outside of WordPress prior to uploading. If I do come across a different solution, I'll be sure to let you know!
