### ISSUE TITLE
Domain Audit

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#2]
firstperson.org and some other domains don't resolve to onbeing.org (primary domain).

**Comment by michiecat** [comment]
https://pantheon.io/docs/domains/ > making sure we have the right CNAME settings...

**Comment by tgilliss** [comment]
This is top priority for us to resolve, but I think it might be easier to fix once we've migrated to Pressable. Do you have the proper Network Solutions permissions @michiecat and @wrightcj03?

**Comment by mariahism** [comment]
Noticed a possibly-related bug, on this page http://onbeing.org/programs/bessel-van-der-kolk-how-trauma-lodges-in-the-body/#comment-3203582108
At the bottom of the page where it says  "Also at On Being" the link for the "Sweet Confinement of Your Aloneness" redirects to this page: http://www.speakingoffaith.org/blog/shireen-qudosi-the-sweet-confinement-of-your-aloneness/

I think this is probably caused by the domain issues we're having. My guess is that someone accessed the SOF site to comment and that's why it might be linked there instead of On Being? The other links do go to onbeing.org.

**Comment by michiecat** [comment]
@tgilliss:

I've pointed the following domains (and their "www" equivalents) to http://onbeing.org:

http://firstperson.org/
http://onbeing.com/
http://speakingoffaith.org (.net, .com)

The link @mariahism pointed out (http://www.speakingoffaith.org/blog/shireen-qudosi-the-sweet-confinement-of-your-aloneness/) now redirects to https://onbeing.org/blog/shireen-qudosi-the-sweet-confinement-of-your-aloneness/). 

Were there any other domains that we should redirect? The rest that were at Network Solutions looked attached to sites already, so I didn't touch those.

**Comment by tgilliss** [comment]
This is fabulous. And all looks like it's working well now. Thank you!
T

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by michiecat** [comment]
No problem, I'll go ahead and close out this issue. :)
