### ISSUE TITLE
BUG: Visual Composer markup is showing up in search results

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#39]
See this link (or attached image) http://onbeing.org/?s=krista+tippett&op=Search&form_build_id=&form_id=search_block_form

![screenshot_2017-03-08_11 46 15](https://cloud.githubusercontent.com/assets/16471307/24466294/03721e58-1476-11e7-979c-9cf9d9c1cf41.png)

**Comment by sarahmonster** [comment]
I can't seem to replicate this issue on the production site:

<img width="975" alt="screenshot 2017-06-06 14 25 17" src="https://cloud.githubusercontent.com/assets/376315/26831385/0b030356-4ac4-11e7-8029-9c1fc8c462e6.png">

I suspect the search code has been altered since this issue was originally posted; see #38 for related issues.

Please feel free to re-open this issue if I've missed something here, though!

**Comment by tgilliss** [comment]
It does appear differently in my tests. Thanks for verifying.

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by sarahmonster** [comment]
@tgilliss could you send me a screenshot and the URL where you're seeing the problem so I can investigate further?

**Comment by tgilliss** [comment]
My view aligns with your view is what I intended to communicate. Cheers.

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403
