### ISSUE TITLE
Older broadcasts still appearing in Google searches

### ISSUE THREAD

**Issue by msambilay** [a8cteam51/onbeing#58]
The episode pages for older broadcasts are still appearing in Google searches, while the pages for new broadcasts are buried in the second or third page of results. (Example search: "Bessel van der Kolk") 

We wouldn't want to completely obscure older pages from Google indexing, since those frequently rank very highly in search results — but wondering whether we should take a closer look at this functionality.

**Comment by wrightcj03** [comment]
Hi @msambilay! This makes sense because links gain authority overtime. While a new episode may not rank above an older episode with the same guest on day 1, search results are fluid and it may later. 

When I searched Bessel van der Kolk, the March 2017 episode was the the first On Being link and the fourth link overall. Is there a more recent episode?

<img width="1245" alt="screen shot 2017-05-24 at 9 16 55 am" src="https://cloud.githubusercontent.com/assets/23107581/26411074/2eaf33c2-4062-11e7-8ef5-4cda6ef05789.png">

If not, I'd suggest closing this issue for now. If you'd like, we can plan to revisit SEO in a dedicated effort after the performance issues are resolved and create new issues with specific goals and KPIs.

**Comment by tgilliss** [comment]
Let's table this issue for now.

Thank you!
T

...................
Trent Gilliss
Chief Content Officer / Executive Editor
On Being + The Civil Conversations Project
 
651.206.2022 / @trentgilliss

1619 Hennepin Ave S
Minneapolis, MN 55403
