### ISSUE TITLE
Bulleted Lists Don't Work on Pages/Visual Composer

### ISSUE THREAD

**Issue by mariahism** [a8cteam51/onbeing#70]
Trying to edit this page: https://onbeing.org/on-being-gathering/

And bulleted lists are not displaying. Would be very helpful to fix. 

![screenshot 2017-05-23 11 19 28](https://cloud.githubusercontent.com/assets/16471307/26364323/8f4aa66c-3fa9-11e7-9ae8-328dcad9115c.png)

**Comment by wrightcj03** [comment]
@tgilliss pointed out that since we merged this issue, bullet points have appeared where they shouldn't. Specifically on the homepage connect section:

![image](https://user-images.githubusercontent.com/23107581/27243855-26c2c3d0-52a1-11e7-8ea5-d1974fe3c25b.png)

Trent resolved the issue with the following CSS (added via the customizer):
```
.content ul {
	list-style-type: none !important;
	margin-left: 0px !important;
}
```

Do we need to do any additional CSS adjustments? (cc @michiecat )

**Comment by michiecat** [comment]
yikes, sorry about that. I'll work on a fix and get it pushed today.

**Comment by tgilliss** [comment]
Thank you.

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Fri, Jun 16, 2017 at 3:47 PM, Michelle Langston <notifications@github.com

**Comment by michiecat** [comment]
@tgilliss @wrightcj03 I've pushed a fix for this that should only display bullets inside visual composer columns. Trent, I left your earlier fix in place for now, so feel free to remove it at your discretion.
