### ISSUE TITLE
Duplicate episode functionality has disappeared

### ISSUE THREAD

**Issue by msambilay** [a8cteam51/onbeing#72]
In the move to Pressable, it looks like we lost the ability to duplicate episode pages.

Previously, we could access this function by hovering on the desired episode in the Episodes list and clicking on the "Duplicate" link that would appear below. Now, the options that appear are only "Edit," "Quick Edit," "Trash," and "View."

**Comment by tgilliss** [comment]
Hi Christie and Michelle—

This is a huge issue since it's lost functionality. Perhaps a certain plugin served this before? I can't imagine that it was a hosting thing.

...................
Trent Gilliss
Chief Content Officer / Executive Editor
On Being + The Civil Conversations Project
 
651.206.2022 / @trentgilliss

1619 Hennepin Ave S
Minneapolis, MN 55403

**Comment by wrightcj03** [comment]
I added the duplicate post plugin to the site and tested to make sure it allows admin and editors to clone episodes (you can also clone posts, pages, and more if you adjust the plugin settings). You should be able to clone a post from the post edit screen, as a bulk action, and in the post table rubric:

<img width="352" alt="screen shot 2017-05-24 at 8 55 04 am" src="https://cloud.githubusercontent.com/assets/23107581/26409927/20d10ea4-405f-11e7-9016-0affe3e7daad.png">

cc @tgilliss @mariahism @msambilay
