### ISSUE TITLE
unexpected text showing on all pages

### ISSUE THREAD

**Issue by tgilliss** [a8cteam51/onbeing#99]
On a Mac laptop using Safari and Chrome, static 'X close' text and extra spacing now displays at the bottom of all pages at onbeing.org. It looks like it should something that only displays for mobile browsers and should be suppressed on desktop versions? Please clean up quickly.

![screenshot 2017-07-31 11 17 33](https://user-images.githubusercontent.com/25962042/28793995-70bd5cd0-75fa-11e7-8e48-1b1091d6cd9e.png)

**Comment by ChrisHardie** [comment]
Hi @tgilliss - we're taking a look at this. That element seems to be a part of the pop-up that encourages visitors to subscribe to the Mailchimp list. Have there been any changes or updates to that setup or other plugins recently? When did you first notice this happening? Thanks.

**Comment by tgilliss** [comment]
Not that I'm aware of, Chris. The only people that are touching the code
are folks from Automattic at this time. One of my team noticed it today but
I'm not sure when it first started happening. Sorry I can't be of more help!

...................
*Trent Gilliss*
Editor-in-Chief / Publisher / Cofounder
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by ChrisHardie** [comment]
Okay, thanks. We haven't made any updates to the live site recently so we're a little stumped too, but we'll track it down.

**Comment by michiecat** [comment]
Hi @tgilliss! Just an update. We've done some more troubleshooting, and it appears that MailChimp made some changes to their hosted-form embed JS code, and that's led to a conflict. It doesn't look like this change is limited to the On Being theme, since we tested the embed code in a fresh WordPress install with a default theme and also on a static HTML page (outside of WordPress) and the same problem occurred. We're currently in touch with MailChimp, and they're taking to look to see if there are any problems on their end. We'll be sure to keep you posted as soon as we have more information.

In the meantime, would you like us to temporarily disable the MailChimp pop-up until we're able to find a fix? Removing the pop-up won't affect your ability to send newsletters to existing subscribers.

**Comment by tgilliss** [comment]
Thanks Michelle. Let's keep the pop-up active for now since it has minimal
effect for users who cancel out of the form. Will you let me know when
MailChimp responds though?

Thank you.
T

...................
*Trent Gilliss*
Editor-in-Chief / Publisher / Cofounder
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Mon, Jul 31, 2017 at 8:20 PM, Michelle Langston <notifications@github.com

**Comment by ChrisHardie** [comment]
@tgilliss We have a ticket open with Mailchimp (#2709269) through our access to your account, to pursue this issue. We'll let you know what they suggest.

**Comment by ChrisHardie** [comment]
@tgilliss we're still going back and forth with Mailchimp support, but from what I can tell in my testing today, this issue is no longer happening. I've loaded a few pages on the site, dismissed the popup and reloaded, and no longer see any unwanted space or text in the footer. Tests by others here in different browsers show the same. We didn't change anything so I'm assuming that Mailchimp did on their end. 

In any case, can you confirm that the issue is no longer present for your team?

**Comment by tgilliss** [comment]
It looks good to me right now. I guess we can close out the issue for now.
Thanks so much for looking into it!
T

...................
*Trent Gilliss*
Editor-in-Chief / Publisher / Cofounder
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403
